name: Docker Build and Deploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  packages: write

env:
  GHCR_REGISTRY: ghcr.io
  DOCKERHUB_REGISTRY: docker.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for GHCR
        id: meta-ghcr
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Extract metadata (tags, labels) for Docker Hub
        id: meta-dockerhub
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Read version from package.json
        id: ver
        run: |
          VER=$(node -p "require('./package.json').version")
          echo "version=$VER" >> $GITHUB_OUTPUT

      - name: Build and push GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta-ghcr.outputs.tags }}
            ghcr.io/${{ github.repository }}:${{ steps.ver.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta-ghcr.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker Hub
        uses: docker/build-push-action@v6
        if: ${{ env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ steps.meta-dockerhub.outputs.tags }}
            docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.ver.outputs.version }}
            docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
          labels: ${{ steps.meta-dockerhub.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set deployment environment variables
        id: deploy-env
        run: |
          echo "server_host=${{ secrets.SERVER_HOST }}" >> $GITHUB_OUTPUT
          echo "server_username=${{ secrets.SERVER_USERNAME }}" >> $GITHUB_OUTPUT
          echo "server_ssh_key=${{ secrets.SERVER_SSH_KEY }}" >> $GITHUB_OUTPUT
          echo "server_port=${{ secrets.SERVER_PORT }}" >> $GITHUB_OUTPUT

      - name: Deploy to server
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && steps.deploy-env.outputs.server_host != '' && steps.deploy-env.outputs.server_username != '' && steps.deploy-env.outputs.server_ssh_key != ''
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # 登录到容器注册表
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            # 停止并删除旧容器
            docker stop strapi-app || true
            docker rm strapi-app || true

            # 删除旧镜像
            docker rmi ghcr.io/${{ github.repository }}:latest || true
            docker rmi docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest || true

            # 拉取最新镜像（优先使用 Docker Hub）
            if [ ! -z "${{ env.DOCKERHUB_USERNAME }}" ]; then
              docker pull docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
              IMAGE_NAME="docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest"
            else
              docker pull ghcr.io/${{ github.repository }}:latest
              IMAGE_NAME="ghcr.io/${{ github.repository }}:latest"
            fi

            # 运行新容器
            docker run -d \
              --name strapi-app \
              --restart unless-stopped \
              -p 1337:1337 \
              -e DATABASE_HOST=${{ secrets.DATABASE_HOST }} \
              -e DATABASE_PORT=${{ secrets.DATABASE_PORT }} \
              -e DATABASE_NAME=${{ secrets.DATABASE_NAME }} \
              -e DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} \
              -e DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e ADMIN_JWT_SECRET=${{ secrets.ADMIN_JWT_SECRET }} \
              -e APP_KEYS=${{ secrets.APP_KEYS }} \
              -e API_TOKEN_SALT=${{ secrets.API_TOKEN_SALT }} \
              -e TRANSFER_TOKEN_SALT=${{ secrets.TRANSFER_TOKEN_SALT }} \
              -v strapi-uploads:/app/public/uploads \
              $IMAGE_NAME

            # 清理未使用的镜像
            docker image prune -f
